onboarding = false

[keys]
prefix = "ctrl+a"
copy_mode = "prefix+v"
split_vertical = "prefix+|"
split_horizontal = "prefix+minus"
rename_tab = ["prefix+shift+t", "prefix+comma"]
rename_workspace = ["prefix+shift+w", "prefix+$"]
settings = "prefix+o"
workspace_picker = "prefix+s"
goto = "prefix+w"

[theme]
name = "catppuccin"

auto_switch = false
[ui]
mouse_capture = true

[terminal]
shell_mode = "auto"

[ui.toast]
delivery = "terminal"

[experimental]
pane_history = true
