icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
[icons]
icons = "material-nf"

[[block]]
block = "kdeconnect"
format = " $icon {$bat_icon $bat_charge |}{$notif_icon |}{$network_icon$network_strength $network_type |}"
bat_good = 101
missing_format = ""

# i3srs config
[[block]]
block = "music"
format = " $icon {$combo.str(max_w:100,rot_interval:0.5) $prev $play $next |}"


[[block]]
block = "backlight"
missing_format = ""

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = " $icon root: $available.eng(w:2) "
# 
# [[block]]
# block = "net"
# format = " $ip"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
missing_format = ""

[[block]]
block = "notify"
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"
